version: '2'
services:
  web:
     build: .
     image: ncrawler/msa_langdetect
     container_name: msa_langdetect
     command: gunicorn
     volumes:
       - .:/application/msa_langdetect
     ports:
       - "21021:21021"
